version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build: ./docker/php-fpm
    volumes:
        - ./src:/var/www
        - ./docker/php-fpm/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - mysql
  workspace:
    build: ./docker/workspace
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    tty: true
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: localuser
      MYSQL_PASSWORD: password
